apiVersion: v1
kind: Pod
metadata:
  name: django-clearsessions
  labels:
    app: backend
spec:
  restartPolicy: OnFailure
  containers:
  - name: clear-sessions-container
    image: clear_sessions_image:0
    env:
    - name: SECRET_KEY
      valueFrom:
        configMapKeyRef:
          name: django-configmap
          key: SECRET_KEY
    - name: DATABASE_URL
      valueFrom:
        configMapKeyRef:
          name: django-configmap
          key: DATABASE_URL
