apiVersion: v1
kind: ConfigMap
metadata:
  name: django-configmap
data:
  SECRET_KEY: "asd"
  DATABASE_URL: "postgres://test_k8s:OwOtBep9Frut@192.168.0.108:5432/test_k8s"
  DEBUG: "false"
  ALLOWED_HOSTS: "*"
