apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-deployment
  labels: 
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: mycontainer
        image: myapp:idk
        envFrom:
        - configMapRef:
            name: django-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
