apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    app: backend
spec:
  containers:
  - name: mycontainer
    image: myapp:idk
    env:
    - name: SECRET_KEY
      value: "asd"
    - name: DATABASE_URL
      value: "postgres://test_k8s:OwOtBep9Frut@192.168.0.108:5432/test_k8s"
    - name: DEBUG
      value: "false"
    - name: ALLOWED_HOSTS
      value: "*"
